name: Security check - Bandit
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Python security check using Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1
        with:
          python_version: ${{ matrix.python-version }}
          project_path: .
          ignore_failure: true
      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Security report
          path: output/security_report.txt
