name: flake8 Lint
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          update-setuptools: "true"
          update-wheel: "true"
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eporter: github-pr-check
