name: pyliny Lint
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pylint-lint:
    runs-on: ubuntu-latest
    name: PyLint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          update-setuptools: "true"
          update-wheel: "true"
      - name: pylint Lint
      - uses: dciborow/action-pylint@0.0.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
