name: Formatting, Style check & linting
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  QA-QC:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "true"
          update-setuptools: "true"
          update-wheel: "true"
      - uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - uses: dciborow/action-pylint@0.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - name: Python security check using Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1
        with:
          python_version: '3.8'
          project_path: minipackage
          ignore_failure: true
